language: node_js
node_js: lts/*
cache:
  directories:
  - node_modules
matrix:
  include:
  - node_js: lts/*
    env: TEST=client
    script: cd $TEST && npm install && npm run test && npm run build
    deploy:
      provider: pages
      skip_cleanup: true
      # keep_history: true
      # target-branch: gh-pages
      # repo: thinktwice13.github.io/bearecipes16
      local-dir: client/build/
      on:
        branch: deployment/client
      verbose: true
      github_token:
        secure: GdTWvdYiz8hg4Q9uytuTABM/ExjY4XDuHEWLY65ws5oOt6Wi5YS8Chohq4K+AjcDz/+s4J9hbvpAXcLItHLcVdcyX9rQbBnWX0Woz72THW4Fkk0rASTqFrAZItye5WODQMqXIkyJDNmJTeOeyDrelhqTZ8tjLRtyjW5LuOhv/YcugfJXfzX+fUdEdJ3DVpuwsU7b42Wk/geFSEYYm/pKyhDd23fvcleGtoMiNI4JrVh1+tbzh7zJ9d+jjjHCctkpivkl4QMRyIQa0aYkcSk+w20iA1juBS4LLC8lanoSX9qWqlmMaPHYz/6+ATTFhdRieS4+xig7kufIGgBGR7mVUzPYBwO0yb1P7LdtC0DKFj9yOm36doWjWHKWkk4wsv+OGR44Haf8l9zzRJsZsdPA1qyrDv88ioELbabOy5hYOGeoNZWNMJZV6e7GIfzY1TPmi1FCH3bK0Ahn38BngAfP14EjOgESLFSgUj1dSbCUhcJgol5xDvOSODOiqQ+Ta42gda1ISyqLnB8AlMEvDYx37A/OE4jK64egcJjvGk8VXwxc93RI+LGEjwVT3ZeXm9IOTk63vP9azFWFmWE74bbwNUvZlyI8w1/unrXyb+BDJ8U4XUQABlNyy03JG2+WxUlMlzv3uCtjJSYzQ03I5c223nypIfODa07WTxolzpqjNkI=
